package hr.project.model

data class Position (
    var id: Int,
    var name: Positions
)

enum class Positions {
    GOALKEEPER,
    LEFT_WING_BACK, LEFT_BACK, CENTER_BACK, RIGHT_BACK, RIGHT_WING_BACK,
    CENTER_DEFENSIVE_MIDFIELDER, LEFT_MIDFIELDER, CENTER_MIDFIELDER, RIGHT_MIDFIELDER, ATTACKING_MIDFIELDER,
    LEFT_WINGER, CENTER_FORWARD, STRIKER, RIGHT_WINGER
}
