micronaut:
  application:
    name: backend
datasources:
  default:
    url: jdbc:mysql://localhost:3306
    driverClassName: com.mysql.cj.jdbc.Driver
    username:
    password:

netty:
  default:
    allocator:
      max-order: 3
